import Head from 'next/head'
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-fit bg-gray-300 m-8 border-4 border-gray-700 shadow-2xl rounded-md flex flex-col">
          <Image src="/logo.jpg" alt="logo" className="rounded-t-md" width="450" height="450"/>
          <h1 className="font-mono text-3xl inline font-bold m-4 text-gray-700">Coding Goose</h1>
          <p className="font-mono text-xl m-4">Tutorials über Smart Home,<br/> Coding Tech uvm.</p>
          <hr className="mt-4 border-gray-400"/>
          <div className="flex justify-around items-center pt-4">
              <div className="font-mono font-bold text-2xl text-gray-700 bg-gray-100 flex-1 text-center py-4 shadow-2xl">
                  Views
              </div>
              <div className="font-mono font-bold text-2xl text-gray-700 bg-gray-100 flex-1 text-center py-8 shadow-2xl">
                  Subs
              </div>
              <div className="font-mono font-bold text-2xl text-gray-700 bg-gray-100 flex-1 text-center py-4 shadow-2xl">
                  Watched
              </div>
          </div>
          <div className="flex justify-around items-center py-2">
              <div className="font-mono text-3xl text-gray-700 flex-1 text-center">
                  14.192
              </div>
              <div className="font-mono text-3xl text-gray-700 flex-1 text-center">
                  124
              </div>
              <div className="font-mono text-3xl text-gray-700 flex-1 text-center">
                  500h
              </div>
          </div>
          <button className="mt-2 p-4 bg-red-600 text-white text-3xl font-mono font-bold">Go to Channel</button>
      </div>
    </div>
  )
}
